services:
  app:
    container_name: 0day
    image: 0day_diary
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # - "host_port:container_port"
      - "4500:4500"
    volumes:
      - type: bind
        source: C:/diary
        target: /0day_diary/data
    restart: unless-stopped