services:
  app:
    container_name: 0day
    image: 0day_diary
    ports:
      - 4500:4500 # host_port:container_port
    volumes:
      # - source(host):target(container)
      # - C:\diary\diary.db:/0day_diary/diary.db
      - type: bind
        source: 'C:/diary'
        target: /0day_diary/data
    restart: always