name: 0day_diary CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies & Run Unit Tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Start Containers
        run: docker compose up -d --build

      - name: Verify container is running
        run: |
          STATUS=$(docker inspect --format='{{.State.Status}}' <CONTAINER_NAME_OR_ID>)
          echo "Container status is: $STATUS"
          if [ "$STATUS" != "running" ]; then
            echo "Error: Container is not running!"
            exit 1
          fi
          
      - name: Fetch Container Logs on Failure
        if: failure()
        run: docker compose logs