name: 0day_diary CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies & Run Unit Tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Start Containers
        run: docker compose up -d --build

      - name: Wait for Container Status
        run: |
          sleep 60
          curl -s -o /dev/null -w "%{http_code}" http://localhost:4500/

      - name: Fetch Container Logs on Failure
        if: failure()
        run: docker compose logs